source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'Segment-Tune'

target 'Segment-Tune_Example' do
  pod 'Segment-Tune', :path => '../'

  target 'Segment-Tune_Tests' do
    inherit! :search_paths
  end
end